In [61]:
from apyori import apriori
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [62]:
df = pd.read_csv("../Section 28 - Apriori/Market_Basket_Optimisation.csv", header=None)
df.tail()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
transactions = []
for i in range(0, 7501) :
    transactions.append([str(df.values[i, j]) for j in range(0,20)])

In [64]:
'''
if product is purchased 3 times per week which means
    min_support = 3 * 7 / total_transactions
    min_support = 21 / 7500
    min_support = 0.003
    
    confidence formula => cart contains (p1, p2)/total cart contains p1
    confidence should not too high since we will eliminate all the rules that might be exist
    min_confidence = 20%
    
    min_lift =3
    
    length is the product combination
'''

#apriory function import
rules = apriori(transactions, \
               min_support= 0.003,\
               min_confidence= 0.2,\
               min_lift=3,\
               max_length=2)

In [65]:
result = list(rules)
result

[]